<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.muehlencord.facessupport</groupId>
  <artifactId>faces-support</artifactId>
  <version>2.0.6</version>
  <packaging>pom</packaging>
  <name>faces-support</name>
  <modules>
    <module>faces-support-parent</module>
    <module>faces-support-bom</module>
    <module>faces-support-spring-data-jpa-spring-boot-starter</module>
    <module>faces-support-spring-data-jpa-spring-boot-autoconfigure</module>
    <module>faces-support-lib</module>
    <module>faces-support-spring-data-jpa</module>
    <module>faces-support-coverage</module>
    <module>faces-support-spring-boot-starter</module>
    <module>faces-support-spring-boot-autoconfigure</module>
    <module>faces-support-demo</module>
  </modules>

  <scm>
    <connection>scm:git:git@github.com:jomu78/faces-support.git</connection>
    <developerConnection>scm:git:git@github.com:jomu78/faces-support.git</developerConnection>
    <url>https://github.com/jomu78/faces-support</url>
    <tag>faces-support-2.0.6</tag>
  </scm>

  <properties>
    <!-- plugin versions -->
    <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
    <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
    <central-publishing-maven-plugin.version>0.10.0</central-publishing-maven-plugin.version>
    <maven-release-plugin.version>3.3.1</maven-release-plugin.version>
  </properties>


  <profiles>
    <profile>
      <id>release</id>
      <build>
        <plugins>
          <!-- automatically create javadoc archive -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <configuration>
              <failOnError>true</failOnError>
              <failOnWarnings>false</failOnWarnings>
            </configuration>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>

          <!-- automatically create source archive -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>${maven-source-plugin.version}</version>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>

          <!-- sign components -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>${maven-gpg-plugin.version}</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <keyname>3448E23404383EEA</keyname>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>


  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <version>${maven-release-plugin.version}</version>
        <configuration>
          <autoVersionSubmodules>true</autoVersionSubmodules>
          <releaseProfiles>release</releaseProfiles>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>



</project>
