<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.muehlencord.facessupport</groupId>
  <artifactId>faces-support</artifactId>
  <version>1.5.14-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>faces-support</name>
  <modules>
    <module>faces-support-parent</module>
    <module>faces-support-bom</module>
    <module>faces-support-spring-data-jpa-spring-boot-starter</module>
    <module>faces-support-spring-data-jpa-spring-boot-autoconfigure</module>
    <module>faces-support-lib</module>
    <module>faces-support-spring-data-jpa</module>
    <module>faces-support-coverage</module>
    <module>faces-support-spring-boot-starter</module>
    <module>faces-support-spring-boot-autoconfigure</module>
    <module>faces-support-demo</module>
  </modules>



</project>
