<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>de.muehlencord.facessupport</groupId>
    <artifactId>faces-support-parent</artifactId>
    <version>2.0.8</version>
    <relativePath>../faces-support-parent/pom.xml</relativePath>
  </parent>

  <artifactId>faces-support-coverage</artifactId>
  <name>faces-support-coverage</name>

  <dependencies>
    <dependency>
      <groupId>de.muehlencord.facessupport</groupId>
      <artifactId>faces-support-lib</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>de.muehlencord.facessupport</groupId>
      <artifactId>faces-support-spring-data-jpa</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>de.muehlencord.facessupport</groupId>
      <artifactId>faces-support-spring-data-jpa-spring-boot-starter</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <configuration>
          <skipPublishing>true</skipPublishing>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
