<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>de.muehlencord.facessupport</groupId>
    <artifactId>faces-support-parent</artifactId>
    <version>1.5.15.1</version>
    <relativePath>../faces-support-parent/pom.xml</relativePath>
  </parent>

  <artifactId>faces-support-spring-data-jpa-spring-boot-autoconfigure</artifactId>
  <name>faces-support-spring-data-jpa-spring-boot-autoconfigure</name>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-autoconfigure</artifactId>
    </dependency>

    <dependency>
      <groupId>de.muehlencord.facessupport</groupId>
      <artifactId>faces-support-spring-data-jpa</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

</project>
